### ISSUE TITLE
regarding YOURDATASET format

### ISSUE THREAD

**Issue by gunahn** [jwc-rad/pix2pix3D-CT#2]
Thank you for making sharing amazing code.

I have a question regarding YOURDATASET format

YOURDATASET
    case1
        CT1 containing dicom files
        CT2 containing dicom files
    case2
        CT1 containing dicom files
        CT2 containing dicom files
    ...

Above is the sample data format that you provide.

And below is the data sample that I am using
case 1
- 1 (another folder)
- - 11.dcm
- - 12.dcm
- - 13.dcm....

-2 (another folder)
--21.dcm
--22.dcm
--23.dcm

case 2 
- 1 (another folder)
- - 11.dcm
- - 12.dcm
- - 13.dcm....

-2 (another folder)
--21.dcm
--22.dcm
--23.dcm
 
<img width="968" alt="image" src="https://user-images.githubusercontent.com/58503653/175893274-b802439b-3428-4367-b994-be7fd7916aca.png">

is this format correct? Can you explain in more detail the proper format I should use?

**Comment by jwc-rad** [comment]
Yes. It looks correct.

**Comment by puallee** [comment]
What is the difference between CT1 and CT2? Is CT1 enhanced CT and CT2 non-enhanced CT? Thanks

**Comment by jwc-rad** [comment]
It would depend on what you are trying to do. If you are trying to generate synthetic enhanced CT out of non-enhanced CT, CT1 would be non-enhanced and CT2 would be enhanced. If you are trying to generate synthetic non-contrast CT out of enhanced CT, it would be the opposite.
