### ISSUE TITLE
Calculating metrics such as MAE, PSNR, MS-SSIM, LPIPS

### ISSUE THREAD

**Issue by gunahn** [jwc-rad/pix2pix3D-CT#3]
Hi, thank you for providing amazing source code. 

In your paper, you mentioned that you calculated MAE, PSNR, MS-SSIM, LPIPS between NCCT and CCT.

Can you provide the code that you calculated MAE, PSNR, MS-SSIM, LPIPS? 

Thank you so much

Best Regards, 

Gun Ahn

**Comment by jwc-rad** [comment]
The packages I used for the metrics are as follows:
1) MAE: [sklearn.metrics.mean_absolute_error](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_error.html)
2) PSNR: [skimage.metrics.peak_signal_noise_ratio](https://scikit-image.org/docs/stable/api/skimage.metrics.html#skimage.metrics.peak_signal_noise_ratio)
3) MS-SSIM: [tf.image_ssim_multiscale](https://www.tensorflow.org/api_docs/python/tf/image/ssim_multiscale)
you have to calculate this as <code>tf.reduce_mean(tf.image.ssim_multiscale(image1, image2))</code>
4) [LPIPS](https://github.com/richzhang/PerceptualSimilarity)

**Comment by gunahn** [comment]
Thank you so much for the quick reply. I truly appreciate it. 

However, there is an issue regarding MS-SSIM. In [tf.image_ssim_multiscale](https://www.tensorflow.org/api_docs/python/tf/image/ssim_multiscale), I need to put img1, img2, max_val. Therefore, the above code that you provided brings some errors.  Did you calculate max_val yourself? Could you explain what did you use or how did you calculate max_val? 

Again, thank you so much

**Comment by jwc-rad** [comment]
It would depend on how you process your images. 
For example, for evaluating the metrics, I applied a mediastinal window to CT images (that is, window width ~400HU, level ~50HU) to get images in value of [0,255]. So max_val was 255, in this case.

**Comment by gunahn** [comment]
Thank you so much. 

I have a question regarding the window as well, I get the DICOM ct images for bone (in PACS -> W:4500, L 500). However, I need to change these images to abdomen configuration(PACS -> W:250, L:50). Do you know how to change the configuration in python code? 

Thank you

**Comment by jwc-rad** [comment]
Do you mean you have your CT images already processed in the bone window? A DICOM file contains raw HU values, not the windowed image. You can apply any window you want.
