### ISSUE TITLE
What is WND? Thank you very much

### ISSUE THREAD

**Issue by puallee** [jwc-rad/pix2pix3D-CT#4]
When I run inference， I find a mistake.  What is WND, thank you very much

Traceback (most recent call last):
  File "inference.py", line 313, in <module>
    samples.append(loop_over_case(L[case], notruth=False))
  File "inference.py", line 229, in loop_over_case
    a.append(WND(dcm_A,w))
NameError: name 'WND' is not defined

def loop_over_case(case, notruth=False):

    pid, zs = case

    dcm_A, dcm_B = gan.data_loader.load_dicoms(pid, (0,zs+1))
    if notruth:
        dcm_A = np.zeros(dcm_B.shape, dtype=dcm_B.dtype)

    a = []
    b = []
    for w in gan.data_loader.window2:
        a.append(WND(dcm_A,w))
    for w in gan.data_loader.window1:
        b.append(WND(dcm_B,w))  
    tot_A = np.stack(a, axis=-1)
    tot_B = np.stack(b, axis=-1)
    tot_A = tot_A.astype('float32')/127.5 - 1.
    tot_B = tot_B.astype('float32')/127.5 - 1.

    fakes_raw = np.full((gan.img_rows,gan.img_cols,zs),0,dtype=tot_B.dtype)
    counts_raw = np.full((gan.img_rows,gan.img_cols,zs),0,dtype=int)

    for i in tqdm_notebook(range(zs+1-gan.depth)):
        imgs_B = np.expand_dims(tot_B[:,:,i:i+gan.depth,:], axis=0)
        fake_A = gan.generator.predict(imgs_B)
        fake_A = 0.5 * fake_A + 0.5
        fake_A = rWND(255.*fake_A[:,:,:,:,0], gan.data_loader.window2[0])

        fakes_raw[:,:,i:i+gan.depth] += fake_A[0]
        counts_raw[:,:,i:i+gan.depth] += 1

    mcounts = counts_raw.copy()
    mcounts[mcounts==0] = 1
    fakes = np.divide(fakes_raw, mcounts)

    # random sample
    sample = np.random.choice(fakes.shape[-1])
    sample = np.stack((
        dcm_B[:,:,sample].astype(fakes.dtype),
        fakes[:,:,sample],
        dcm_A[:,:,sample].astype(fakes.dtype)
    ), axis=-1)

    df1 = gan.data_loader.df
    dcms1 = df1[(df1['pid']==pid)&(df1['ct']==gan.data_loader.cts[0])]['filepath'].tolist()

    newpath = os.path.join(savedir, pid)
    if not os.path.isdir(newpath):
        os.mkdir(newpath)
    newpath = os.path.join(newpath, 'dicom')
    if not os.path.isdir(newpath):
        os.mkdir(newpath)

    for N, y in tqdm_notebook(enumerate(dcms1)):
        x = fakes[:,:,N]
        ds = pydicom.dcmread(y)

        x = (x-float(ds.RescaleIntercept))/float(ds.RescaleSlope)

        x = x.astype('int16')

        ds.PixelData = x.tobytes()

        ds.SeriesNumber += 99000
        ds.SOPInstanceUID += '.99'

        newfile = os.path.join(newpath, os.path.basename(y))
        ds.save_as(newfile)

    return sample

**Comment by jwc-rad** [comment]
It is defined in [source/data_loader.py](https://github.com/jwc-rad/pix2pix3D-CT/blob/a2dd01780b39b8c2e7bcd5dd99f45a602f58e79c/source/data_loader.py#L11). I have updated the notebook file.

**Comment by puallee** [comment]
Thanks for your kind reply， What is rWND? Thank you very much 
Traceback (most recent call last):
  File "inference.py", line 332, in <module>
    samples.append(loop_over_case(L[case], notruth=False))
  File "inference.py", line 248, in loop_over_case
    fake_A = rWND(255.*fake_A[:,:,:,:,0], gan.data_loader.window2[0])
NameError: name 'rWND' is not defined

**Comment by jwc-rad** [comment]
[rWND](https://github.com/jwc-rad/pix2pix3D-CT/blob/3eb62b28280094aa4f339ebcfc0b765f5e5cdc45/source/data_loader.py#L17) converts 0~255 image back to CT HU values based on CT window. I have updated the source code.
