### ISSUE TITLE
  Some question about output and dataset

### ISSUE THREAD

**Issue by puallee** [jwc-rad/pix2pix3D-CT#5]
Thanks for your great work！ Whether the code can convert enhanced CT to non-enhanced CT, that is, to fake-B; Are your training data sets, enhanced CT, and non-enhanced CT paired? How to ensure that the CTs  from the same individual with the same breathing time, and there is no deformation between CTs

**Comment by jwc-rad** [comment]
You are correct about the pairing issue. The non-enhanced CT of the training data in our work was virtual non-contrast (VNC) from dual-energy CT.
