### ISSUE TITLE
Generate different image size from original images

### ISSUE THREAD

**Issue by xackey2001** [jwc-rad/pix2pix3D-CT#6]
Thank you for sharing the code.  
I would like to ask, how to change output image size. For example, when the original image size is 512 x 512 x 64, is it possible to generate higher resolution images, such as 1024 x 1024 x 256? 
Also, does the number of CT slices used for training have to be the same for all patients?

xackey

**Comment by jwc-rad** [comment]
Although it is possible to change the output image size, you would have to change the network structure itself to do so.
And yes, the number of CT slices should remain the same.

**Comment by xackey2001** [comment]
Thank you for your reply.
Can we increase the output image size by increasing the number of deconvolution? We can change the number of deconvolution If we revise the code below (build_generator). Am I correct?
https://github.com/jwc-rad/pix2pix3D-CT/blob/main/source/my3dpix2pix.py#L212-L230

**Comment by jwc-rad** [comment]
Yes, I believe so. But I suggest you search for other codes regarding image super-resolution for more recent network structures.

**Comment by xackey2001** [comment]
Thank you for the kind suggestion.
I will search other new networks.
